func language()
If IniRead($Setting,"Langue","Langue","Erreur") = 0 Then
$Section="Francais"
ElseIf IniRead($Setting,"Langue","Langue","Erreur") = 1 Then
$Section="English"
Else
$Section="Espanol"
EndIf
;;;;;;;;;;;;;;; TABS + PRIVE ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
$IniPriveOnTop = iniRead($Setting, $Section, "Ontop", "Erreur")
GUICtrlSetData($PriveOnTop,$IniPriveOnTop)
GUICtrlSetData($ListeOnTop,$IniPriveOnTop)
$IniTransparenceGeneral = iniRead($Setting, $Section, "Transparence", "Erreur")
GUICtrlSetData($TransparenceGeneral,$IniTransparenceGeneral)
GUICtrlSetData($TransparenceDeblo,$IniTransparenceGeneral)
GUICtrlSetData($TransparenceStopChute,$IniTransparenceGeneral)
GUICtrlSetData($TransparenceTP,$IniTransparenceGeneral)
$IniAbout = iniRead($Setting, $Section, "About", "Erreur")
GUICtrlSetData($About,$IniAbout)
$IniOptions = iniRead($Setting, $Section, "Options", "Erreur")
GUICtrlSetData($Optionsbutton,$IniOptions)
$IniTabPrive = iniRead($Setting, $Section, "OngletPrive", "Erreur")
GUICtrlSetData($tab0,$IniTabPrive)
GUICtrlSetData($LaunchPrivateGRP,$IniTabPrive)
$IniGRPLblTeleportation = iniRead($Setting, $Section, "GROUPTeleportation", "Erreur")
GUICtrlSetData($PriveTeleportationGRP,$IniGRPLblTeleportation)
$IniGRPLblJcj = iniRead($Setting, $Section, "GROUPPvP", "Erreur")
GUICtrlSetData($PrivePVPGRP,$IniGRPLblJcj)
$IniGRPLblPistage = iniRead($Setting, $Section, "GROUPTracking", "Erreur")
GUICtrlSetData($PriveTrackingGRP,$IniGRPLblPistage)
GUICtrlSetData($TrackingGRP,$IniGRPLblPistage)
GUICtrlSetData($LBLLaunchTrackPrivate,$IniGRPLblPistage)
GUICtrlSetData($LBLLaunchTrackOfficiel,$IniGRPLblPistage)
$IniLblCooActuel = iniRead($Setting, $Section, "CooActuel", "Erreur")
GUICtrlSetData($LBLCooActuel,$IniLblCooActuel)
$IniLblTeleport = iniRead($Setting, $Section, "Teleporter", "Erreur")
GUICtrlSetData($PriveGoTP,$IniLblTeleport)
GUICtrlSetData($listTeleportGO,$IniLblTeleport)
$IniLblTPcorps = iniRead($Setting, $Section, "TPcorps", "Erreur")
GUICtrlSetData($PriveGoCorps,$IniLblTPcorps)
GUICtrlSetData($LBLSCGocorps,$IniLblTPcorps)
$IniLblActiverXYZ = iniRead($Setting, $Section, "ActiverXYZ", "Erreur")
GUICtrlSetData($LBLActiverXYZ,$IniLblActiverXYZ)
GUICtrlSetData($LBLActiverXYZOf,$IniLblActiverXYZ)
GUICtrlSetData($LBLLaunchXYZPrivate,$IniLblActiverXYZ)
GUICtrlSetData($LBLLaunchXYZOfficiel,$IniLblActiverXYZ)
$IniLblVitesseXYZ = iniRead($Setting, $Section, "VitesseXYZ", "Erreur")
GUICtrlSetData($LBLVitesseXYZ,$IniLblVitesseXYZ)
$IniLblListe = iniRead($Setting, $Section, "Liste", "Erreur")
GUICtrlSetData($ListOuvrir,$IniLblListe)
$IniLblTPcibledos = iniRead($Setting, $Section, "TPcibledos", "Erreur")
GUICtrlSetData($PriveTPcibleDos,$IniLblTPcibledos)
GUICtrlSetData($LBLSCTPcibledos,$IniLblTPcibledos)
$IniLblTPcibleundermap = iniRead($Setting, $Section, "TPcibleundermap", "Erreur")
GUICtrlSetData($PriveTPcibleUndermap,$IniLblTPcibleundermap)
GUICtrlSetData($LBLSCTPcibleundermap,$IniLblTPcibleundermap)
$IniLBLSCSpeedglobale = iniRead($Setting, $Section, "Speedglobale", "Erreur")
GUICtrlSetData($LblSpeedglobale,$IniLBLSCSpeedglobale)
GUICtrlSetData($LBLSCSpeedglobale,$IniLBLSCSpeedglobale)
$IniLblSpeed = iniRead($Setting, $Section, "Speed", "Erreur")
GUICtrlSetData($LBLSpeed,$IniLblSpeed)
GUICtrlSetData($LBLVitesseTemps,$IniLblSpeed)
GUICtrlSetData($LBLSCSpeed,$IniLblSpeed)
GUICtrlSetData($PriveSCsettingsGUIGRPSpeed,$IniLblSpeed)
GUICtrlSetData($LBLLaunchSpeed,$IniLblSpeed)
$IniLblFlymod = iniRead($Setting, $Section, "Flymod", "Erreur")
GUICtrlSetData($LBLFlymod,$IniLblFlymod)
GUICtrlSetData($LBLSCFlymod,$IniLblFlymod)
GUICtrlSetData($LBLLaunchFly,$IniLblFlymod)
$IniLblWalkonwater = iniRead($Setting, $Section, "Walkonwater", "Erreur")
GUICtrlSetData($LBLWalkonwater,$IniLblWalkonwater)
GUICtrlSetData($LBLWaterWalkOf,$IniLblWalkonwater)
$IniLblUnderwaterWalk = iniRead($Setting, $Section, "Walkunderwater", "Erreur")
GUICtrlSetData($LBLUnderwaterWalk,$IniLblUnderwaterWalk)
GUICtrlSetData($LBLUnderwaterWalkOf,$IniLblUnderwaterWalk)
$IniLblMount = iniRead($Setting, $Section, "Mount", "Erreur")
GUICtrlSetData($LBLMount,$IniLblMount)
$IniLblMultijump = iniRead($Setting, $Section, "Multijump", "Erreur")
GUICtrlSetData($LBLInfiniteJump,$IniLblMultijump)
$IniLblNoclip = iniRead($Setting, $Section, "NoClip", "Erreur")
GUICtrlSetData($LBLNoclip,$IniLblNoclip)
$IniLblFreezez = iniRead($Setting, $Section, "Freezez", "Erreur")
GUICtrlSetData($LBLFreezez,$IniLblFreezez)
GUICtrlSetData($LBLSCFreezeZ,$IniLblFreezez)
$IniLblWallclimb = iniRead($Setting, $Section, "Wallclimb", "Erreur")
GUICtrlSetData($LBLWallclimb,$IniLblWallclimb)
GUICtrlSetData($LBLWallclimbOf,$IniLblWallclimb)
GUICtrlSetData($LBLSCWallclimbOf,$IniLblWallclimb)
GUICtrlSetData($LBLSCWallclimb,$IniLblWallclimb)
GUICtrlSetData($LBLLaunchWallClimbPrivate,$IniLblWallclimb)
GUICtrlSetData($LBLLaunchWallclimbOfficiel,$IniLblWallclimb)
$IniLblSupersaut = iniRead($Setting, $Section, "Super-Saut", "Erreur")
GUICtrlSetData($LBLSupersaut,$IniLblSupersaut)
GUICtrlSetData($LBLSupersautOf,$IniLblSupersaut)
GUICtrlSetData($LBLSCSupersautOf,$IniLblSupersaut)
GUICtrlSetData($LBLSCSupersaut,$IniLblSupersaut)
GUICtrlSetData($LBLLaunchSupersautPrivate,$IniLblSupersaut)
GUICtrlSetData($LBLLaunchSupersautOfficiel,$IniLblSupersaut)
$IniLblCollisionsM2 = iniRead($Setting, $Section, "CollisionsM2", "Erreur")
GUICtrlSetData($LBLPriveCollisionsM2,$IniLblCollisionsM2)
GUICtrlSetData($LBLCollisionsM2Of,$IniLblCollisionsM2)
$IniLblCollisionsWMO = iniRead($Setting, $Section, "CollisionsWMO", "Erreur")
GUICtrlSetData($LBLPriveCollisionsWMO,$IniLblCollisionsWMO)
GUICtrlSetData($LBLCollisionsWMOOf,$IniLblCollisionsWMO)
$IniLblDebloPerso = iniRead($Setting, $Section, "Debloperso", "Erreur")
GUICtrlSetData($PriveDebloPerso,$IniLblDebloPerso)
GUICtrlSetData($LBLSCDebloperso,$IniLblDebloPerso)
$IniLblStopchute = iniRead($Setting, $Section, "Stopchute", "Erreur")
GUICtrlSetData($StopchuteON,$IniLblStopchute)
GUICtrlSetData($LBLSCStopchute,$IniLblStopchute)
$IniLblHerbes = iniRead($Setting, $Section, "Herbes", "Erreur")
GUICtrlSetData($PriveTrackHerbes,$IniLblHerbes)
GUICtrlSetData($TrackHerbes,$IniLblHerbes)
$IniLblFilons = iniRead($Setting, $Section, "Filons", "Erreur")
GUICtrlSetData($PriveTrackFilons,$IniLblFilons)
GUICtrlSetData($TrackFilons,$IniLblFilons)
$IniLblCoffres = iniRead($Setting, $Section, "Coffres", "Erreur")
GUICtrlSetData($PriveTrackCoffres,$IniLblCoffres)
GUICtrlSetData($TrackCoffres,$IniLblCoffres)
$IniLblPoissons = iniRead($Setting, $Section, "Poissons", "Erreur")
GUICtrlSetData($PriveTrackPoissons,$IniLblPoissons)
GUICtrlSetData($TrackPoissons,$IniLblPoissons)
$IniLblBetes = iniRead($Setting, $Section, "Betes", "Erreur")
GUICtrlSetData($PriveTrackBetes,$IniLblBetes)
GUICtrlSetData($TrackBetes,$IniLblBetes)
$IniLblDragons = iniRead($Setting, $Section, "Dragons", "Erreur")
GUICtrlSetData($PriveTrackDragons,$IniLblDragons)
GUICtrlSetData($TrackDragons,$IniLblDragons)
$IniLblDemons = iniRead($Setting, $Section, "Demons", "Erreur")
GUICtrlSetData($PriveTrackDemons,$IniLblDemons)
GUICtrlSetData($TrackDemons,$IniLblDemons)
$IniLblElementaires = iniRead($Setting, $Section, "Elementaires", "Erreur")
GUICtrlSetData($PriveTrackElementaires,$IniLblElementaires)
GUICtrlSetData($TrackElementaires,$IniLblElementaires)
$IniLblGeants = iniRead($Setting, $Section, "Geants", "Erreur")
GUICtrlSetData($PriveTrackGeants,$IniLblGeants)
GUICtrlSetData($TrackGeants,$IniLblGeants)
$IniLblMortsVivants = iniRead($Setting, $Section, "Morts-vivants", "Erreur")
GUICtrlSetData($PriveTrackMortsVivants,$IniLblMortsVivants)
GUICtrlSetData($TrackMortsVivants,$IniLblMortsVivants)
$IniLblHumanoides = iniRead($Setting, $Section, "Humanoides", "Erreur")
GUICtrlSetData($PriveTrackHumanoides,$IniLblHumanoides)
GUICtrlSetData($TrackHumanoides,$IniLblHumanoides)
$IniLblBestioles = iniRead($Setting, $Section, "Bestioles", "Erreur")
GUICtrlSetData($PriveTrackBestioles,$IniLblBestioles)
GUICtrlSetData($TrackBestioles,$IniLblBestioles)
$IniLblTout = iniRead($Setting, $Section, "Tout", "Erreur")
GUICtrlSetData($PriveTrackAllBet,$IniLblTout)
GUICtrlSetData($PriveTrackAllRes,$IniLblTout)
GUICtrlSetData($TrackAllBet,$IniLblTout)
GUICtrlSetData($TrackAllRes,$IniLblTout)
$IniLblRaccourcis = iniRead($Setting, $Section, "Raccourcis", "Erreur")
GUICtrlSetData($PriveSCsettings,$IniLblRaccourcis)
GUICtrlSetData($SCsettings,$IniLblRaccourcis)
GUICtrlSetData($LBLLaunchRaccourcisPrivate,$IniLblRaccourcis)
GUICtrlSetData($LBLLaunchRaccourcisOfficiel,$IniLblRaccourcis)
$IniLblPourcents = iniRead($Setting, $Section, "Pourcents", "Erreur")
GUICtrlSetData($LBLSpeedPourcent1,$IniLblPourcents)
;;;;;;;;;;;;;;; OFFICIEL ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
$IniTabOfficiel = iniRead($Setting, $Section, "OngletOfficiel", "Erreur")
GUICtrlSetData($tab1,$IniTabOfficiel)
GUICtrlSetData($LaunchOfficielGRP,$IniTabOfficiel)
$IniLblAutoOf = iniRead($Setting, $Section, "Automatique", "Erreur")
GUICtrlSetData($TPauto,$IniLblAutoOf)
$IniLblManuOf = iniRead($Setting, $Section, "Manuel", "Erreur")
GUICtrlSetData($TPmanu,$IniLblManuOf)

;;;;;;;;;;;;;;; JOUEUR ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
$IniTabAffichage = iniRead($Setting, $Section, "OngletAffichage", "Erreur")
GUICtrlSetData($tab2,$IniTabAffichage)
$IniLblScaleGRP = iniRead($Setting, $Section, "Taille", "Erreur")
GUICtrlSetData($PlayerTailleGRP,$IniLblScaleGRP)
$IniLblScaleP = iniRead($Setting, $Section, "Taillep", "Erreur")
GUICtrlSetData($PlayerTailleP,$IniLblScaleP)
GUICtrlSetData($LBLSCTailleP,$IniLblScaleP)
$IniLblScaleM = iniRead($Setting, $Section, "Taillem", "Erreur")
GUICtrlSetData($PlayerTailleM,$IniLblScaleM)
GUICtrlSetData($LBLSCTailleM,$IniLblScaleM)
$IniLblScale = iniRead($Setting, $Section, "Taille", "Erreur")
GUICtrlSetData($LBLTaille,$IniLblScale)
$IniLblHauteur = iniRead($Setting, $Section, "Hauteur", "Erreur")
GUICtrlSetData($LBLHauteur,$IniLblHauteur)
$IniLblLargeur = iniRead($Setting, $Section, "Largeur", "Erreur")
GUICtrlSetData($LBLLargeur,$IniLblLargeur)
$IniLblAlcool = iniRead($Setting, $Section, "Alcool", "Erreur")
GUICtrlSetData($LBLAlcool,$IniLblAlcool)
$IniLblAffichage = iniRead($Setting, $Section, "GROUPAffichage", "Erreur")
GUICtrlSetData($PlayerShowGRP,$IniLblAffichage)
$IniLblMort = iniRead($Setting, $Section, "Mort", "Erreur")
GUICtrlSetData($LBLMort,$IniLblMort)
$IniLblDevoilerCarte = iniRead($Setting, $Section, "DevoilerCarte", "Erreur")
GUICtrlSetData($MapSHOW,$IniLblDevoilerCarte)
$IniLblCamera = iniRead($Setting, $Section, "GROUPCamera", "Erreur")
GUICtrlSetData($CameraGRP,$IniLblCamera)
$IniLblSpectateur = iniRead($Setting, $Section, "Spectateur", "Erreur")
GUICtrlSetData($LBLSpectateur,$IniLblSpectateur)
$IniLblFollowTar = iniRead($Setting, $Section, "Suivrecible", "Erreur")
GUICtrlSetData($LBLFollowTar,$IniLblFollowTar)
GUICtrlSetData($LBLNoclipCamera,$IniLblNoclip)
$IniLblTemps = iniRead($Setting, $Section, "Temps", "Erreur")
GUICtrlSetData($TempsGRP,$IniLblTemps)
$IniLblHeures = iniRead($Setting, $Section, "Heures", "Erreur")
GUICtrlSetData($LBLHeure,$IniLblHeures)
$IniLblTpCam = iniRead($Setting, $Section, "TPcam", "Erreur")
GUICtrlSetData($PriveTeleportCamera,$IniLblTpCam)
$IniLblEmote = iniRead($Setting, $Section, "Emote", "Erreur")
GUICtrlSetData($LBLEmote,$IniLblEmote)
;;;;;;;;;;;;;;; STOP CHUTE + DEBLOQUER + LISTE + RACCOURCIS ;;;;;;;;;;;;;;;
$IniLblStopchutebutton = iniRead($Setting, $Section, "Stopchutebutton", "Erreur")
GUICtrlSetData($Stopchutebutton,$IniLblStopchutebutton)
$IniLbllisteweh = iniRead($Setting, $Section, "Listeweh", "Erreur")
GUICtrlSetData($LVLlisteweh,$IniLbllisteweh)
$IniLblAddTP = iniRead($Setting, $Section, "AddTP", "Erreur")
GUICtrlSetData($AddTP,$IniLblAddTP)
$IniLblAddTPGRP = iniRead($Setting, $Section, "GROUPAddTP", "Erreur")
GUICtrlSetData($AddTPGRP,$IniLblAddTPGRP)
$IniLblDelTP = iniRead($Setting, $Section, "DelTP", "Erreur")
GUICtrlSetData($DelTP,$IniLblDelTP)
$IniLblDelTPGRP = iniRead($Setting, $Section, "GROUPDelTP", "Erreur")
GUICtrlSetData($DelTPGRP,$IniLblDelTPGRP)
$IniLblNomTP = iniRead($Setting, $Section, "NomTP", "Erreur")
GUICtrlSetData($LBLNomTP,$IniLblNomTP)
$IniLblTPNumber = iniRead($Setting, $Section, "TPNumber", "Erreur")
GUICtrlSetData($LBLTPNumber,$IniLblTPNumber)
$IniLblMapActuelle = iniRead($Setting, $Section, "MapActuelle", "Erreur")
GUICtrlSetData($LBLMapActuelle,$IniLblMapActuelle)
$IniLblDebloPersoButton = iniRead($Setting, $Section, "Deblopersobutton", "Erreur")
GUICtrlSetData($DebloPersobutton,$IniLblDebloPersoButton)

$IniLBLSCSpeedN = iniRead($Setting, $Section, "SpeedN", "Erreur")
GUICtrlSetData($LBLSCSpeedN,$IniLBLSCSpeedN)
$IniLBLSCSpeed100 = iniRead($Setting, $Section, "Speed100", "Erreur")
GUICtrlSetData($LBLSCSpeed100,$IniLBLSCSpeed100)
$IniLBLSCSpeedP = iniRead($Setting, $Section, "SpeedP", "Erreur")
GUICtrlSetData($LBLSCSpeedP,$IniLBLSCSpeedP)
$IniLBLSCSpeedM = iniRead($Setting, $Section, "SpeedM", "Erreur")
GUICtrlSetData($LBLSCSpeedM,$IniLBLSCSpeedM)
$IniLBLSCSpeedFlyN= iniRead($Setting, $Section, "SpeedFlyN", "Erreur")
GUICtrlSetData($LBLSCSpeedFlyN,$IniLBLSCSpeedFlyN)
$IniLBLSCSpeedFly280 = iniRead($Setting, $Section, "SpeedFly280", "Erreur")
GUICtrlSetData($LBLSCSpeedFly280,$IniLBLSCSpeedFly280)
$IniLBLSCSpeedFlyP = iniRead($Setting, $Section, "SpeedFlyP", "Erreur")
GUICtrlSetData($LBLSCSpeedFlyP,$IniLBLSCSpeedFlyP)
$IniLBLSCSpeedFlyM = iniRead($Setting, $Section, "SpeedFlyM", "Erreur")
GUICtrlSetData($LBLSCSpeedFlyM,$IniLBLSCSpeedFlyM)
$IniPriveSCsettingsGUIGRPDivers = iniRead($Setting, $Section, "GRPDivers", "Erreur")
GUICtrlSetData($PriveSCsettingsGUIGRPDivers,$IniPriveSCsettingsGUIGRPDivers)
$IniLBLSCSupersautP= iniRead($Setting, $Section, "SupersautP", "Erreur")
GUICtrlSetData($LBLSCSupersautP,$IniLBLSCSupersautP)
$IniLBLSCSupersautM = iniRead($Setting, $Section, "SupersautM", "Erreur")
GUICtrlSetData($LBLSCSupersautM,$IniLBLSCSupersautM)
$IniLBLSCTimeSpeedP = iniRead($Setting, $Section, "TimeSpeedP", "Erreur")
GUICtrlSetData($LBLSCTimeSpeedP,$IniLBLSCTimeSpeedP)
$IniLBLSCTimeSpeedM = iniRead($Setting, $Section, "TimeSpeedM", "Erreur")
GUICtrlSetData($LBLSCTimeSpeedM,$IniLBLSCTimeSpeedM)
$IniPriveSCsettingsGUIGRPPvP = iniRead($Setting, $Section, "JcjSC", "Erreur")
GUICtrlSetData($PriveSCsettingsGUIGRPPvP,$IniPriveSCsettingsGUIGRPPvP)
$IniPriveSCsettingsGUIGRPGoulet = iniRead($Setting, $Section, "Goulet", "Erreur")
GUICtrlSetData($PriveSCsettingsGUIGRPGoulet,$IniPriveSCsettingsGUIGRPGoulet)
$IniPriveSCsettingsGUIGRPOeil = iniRead($Setting, $Section, "Oeil", "Erreur")
GUICtrlSetData($PriveSCsettingsGUIGRPOeil,$IniPriveSCsettingsGUIGRPOeil)
$IniLLBLSCGouletFlagA2 = iniRead($Setting, $Section, "FlagA2", "Erreur")
GUICtrlSetData($LBLSCGouletFlagA2,$IniLLBLSCGouletFlagA2)
$IniLLBLSCGouletRegenA2 = iniRead($Setting, $Section, "RegenA2", "Erreur")
GUICtrlSetData($LBLSCGouletRegenA2,$IniLLBLSCGouletRegenA2)
$IniLLBLSCGouletBersekerA2 = iniRead($Setting, $Section, "BersekerA2", "Erreur")
GUICtrlSetData($LBLSCGouletBersekerA2,$IniLLBLSCGouletBersekerA2)
$IniLLBLSCGouletSprintA2 = iniRead($Setting, $Section, "SprintA2", "Erreur")
GUICtrlSetData($LBLSCGouletSprintA2,$IniLLBLSCGouletSprintA2)
$IniLLBLSCGouletFlagH2 = iniRead($Setting, $Section, "FlagH2", "Erreur")
GUICtrlSetData($LBLSCGouletFlagH2,$IniLLBLSCGouletFlagH2)
$IniLLBLSCGouletRegenH2 = iniRead($Setting, $Section, "RegenH2", "Erreur")
GUICtrlSetData($LBLSCGouletRegenH2,$IniLLBLSCGouletRegenH2)
$IniLLBLSCGouletBersekerH2 = iniRead($Setting, $Section, "BersekerH2", "Erreur")
GUICtrlSetData($LBLSCGouletBersekerH2,$IniLLBLSCGouletBersekerH2)
$IniLLBLSCGouletSprintH2 = iniRead($Setting, $Section, "SprintH2", "Erreur")
GUICtrlSetData($LBLSCGouletSprintH2,$IniLLBLSCGouletSprintH2)
$IniLBLSCArathiEcurie = iniRead($Setting, $Section, "Ecurie", "Erreur")
GUICtrlSetData($LBLSCArathiEcurie,$IniLBLSCArathiEcurie)
$IniLBLSCArathiFerme = iniRead($Setting, $Section, "Ferme", "Erreur")
GUICtrlSetData($LBLSCArathiFerme,$IniLBLSCArathiFerme)
$IniLBLSCArathiMine = iniRead($Setting, $Section, "Mine", "Erreur")
GUICtrlSetData($LBLSCArathiMine,$IniLBLSCArathiMine)
$IniLBLSCArathiForge = iniRead($Setting, $Section, "Forge", "Erreur")
GUICtrlSetData($LBLSCArathiForge,$IniLBLSCArathiForge)
$IniLBLSCArathiScierie = iniRead($Setting, $Section, "Scierie", "Erreur")
GUICtrlSetData($LBLSCArathiScierie,$IniLBLSCArathiScierie)
$IniLBLSCOeilDrapeau = iniRead($Setting, $Section, "Flag", "Erreur")
GUICtrlSetData($LBLSCOeilDrapeau,$IniLBLSCOeilDrapeau)
$IniLBLSCOeilTourMages = iniRead($Setting, $Section, "TourMages", "Erreur")
GUICtrlSetData($LBLSCOeilTourMages,$IniLBLSCOeilTourMages)
$IniLBLSCOeilRuinesDraenei = iniRead($Setting, $Section, "RuinesDraenei", "Erreur")
GUICtrlSetData($LBLSCOeilRuinesDraenei,$IniLBLSCOeilRuinesDraenei)
$IniLBLSCOeilTourElfes = iniRead($Setting, $Section, "TourElfes", "Erreur")
GUICtrlSetData($LBLSCOeilTourElfes,$IniLBLSCOeilTourElfes)
$IniLBLSCOeilRuinesSaccageur = iniRead($Setting, $Section, "RuinesSaccageur", "Erreur")
GUICtrlSetData($LBLSCOeilRuinesSaccageur,$IniLBLSCOeilRuinesSaccageur)
$IniLBLSCAlteracA2 = iniRead($Setting, $Section, "CoteA2", "Erreur")
GUICtrlSetData($LBLSCAlteracA2,$IniLBLSCAlteracA2)
$IniLBLSCAlteracH2 = iniRead($Setting, $Section, "CoteH2", "Erreur")
GUICtrlSetData($LBLSCAlteracH2,$IniLBLSCAlteracH2)
$IniLBLInterfaceOff = iniRead($Setting, $Section, "InterfaceOff", "Erreur")
GUICtrlSetData($LBLInterfaceOff,$IniLBLInterfaceOff)
$IniLBLContinueOnExit = iniRead($Setting, $Section, "ContinueOnExit", "Erreur")
GUICtrlSetData($LBLContinueOnExit,$IniLBLContinueOnExit)
$IniLBLSaveSettings = iniRead($Setting, $Section, "SaveSettings", "Erreur")
GUICtrlSetData($LBLSaveSettings,$IniLBLSaveSettings)
$IniLangueGRP = iniRead($Setting, $Section, "Langage", "Erreur")
GUICtrlSetData($LangueGRP,$IniLangueGRP)

GUICtrlSetData($LBLSCSpeedcustom,$IniLblSpeed&" =")
$INILBLSCSpeedFlycustom = iniRead($Setting, $Section, "FlySpeedCustom", "Erreur")
GUICtrlSetData($LBLSCSpeedFlycustom,$INILBLSCSpeedFlycustom)
endfunc
